### ISSUE TITLE
Bump dependencies of cardano-api and GHC

### ISSUE THREAD

**Issue by mmontin** [IntersectMBO/cardano-node-emulator#22]
I use cardano-node-emulator as part of my work and it seems that the current version of cardano-api and associated libraries is oudated on branch Conway. In addition, the current version of GHC used in the repository 9.6.2 is discouraged. Updating this dependency would also allow for a more recent and stable version of HLS. Overall, I would suggest to bump the versions of
- cardano-api (current release is 8.46)
- GHC from 9.6.2 to 9.6.5

**Comment by smelc** [comment]
Updating GHC to 9.6.5 cannot be done at the moment because [haskell.nix](https://github.com/input-output-hk/haskell.nix) doesn't seem to super it nicely, so this is not planned for now.
