### ISSUE TITLE
cardano-api version should be compatible with cardano-node

### ISSUE THREAD

**Issue by kayvank** [IntersectMBO/cardano-node-emulator#23]
The restriction on the cardano-api ^=8.42 version is such that it prevents us from using 
cardano-node 8.73
cardano-node 8.93
cardano-node 8.11*

See cardano-node release notes for detail

**Comment by smelc** [comment]
@kayvank> any specific version of `cardano-api` you would prefer

---

Related: https://github.com/IntersectMBO/cardano-node-emulator/issues/22

**Comment by kayvank** [comment]
> @kayvank> any specific version of `cardano-api` you would prefer?
> 
> Related: #22

cardano-api-8.46 is my preference as it is targeted by cardano-node 8.11.  As cardano-dev team is working on 8.11.1 as a mainnet release now

**Comment by kayvank** [comment]
FYI, the cardano-node-emulator has a dependency of the quickcheck-contractmodel, and quickcheck-contractmodel also has to be upgraded in regards to plutus-tx and cardano-api. I have the related [PR-40](https://github.com/input-output-hk/quickcheck-contractmodel/pull/40) for that work

**Comment by smelc** [comment]
Thanks @kayvank for the context :+1: Will try to make it happen
